# Global
brew "akopdev/formulas/nbcat", trusted: true
brew "awscli"
brew "basedpyright"
brew "bash-language-server"
brew "bat"
brew "bc"
brew "cask"
brew "charmbracelet/tap/crush", trusted: true
brew "ec"
brew "cookiecutter"
brew "ctop"
brew "dockerfile-language-server"
brew "dosfstools"
brew "eslint"
brew "eza"
brew "fd"
brew "fx"
brew "fzf"
brew "gh"
brew "git"
brew "git-delta"
brew "glow"
brew "gnupg"
brew "go"
brew "gopls"
brew "hashicorp/tap/terraform", trusted: true
brew "helm"
brew "htop"
brew "hugo"
brew "imagemagick"
brew "irssi"
brew "jq"
brew "k9s"
brew "kubernetes-cli"
brew "lazysql"
brew "lua-language-server"
brew "mtools"
brew "ncdu"
brew "neovim"
brew "node"
brew "ollama"
brew "pass"
brew "pgcli"
brew "php"
brew "podman"
brew "podman-compose"
brew "profanity"
brew "python@3.13"
brew "qemu"
brew "ripgrep"
brew "dart-sass", trusted: true
brew "sheets"
brew "tea"
brew "terraform-ls"
brew "tmux"
brew "typescript"
brew "typescript-language-server"
brew "uv"
brew "wget"
brew "wifitui"
brew "xclip"
brew "yaml-language-server"
brew "yarn", link: false
brew "zinit"
brew "zk"

cargo "ghgrab"

# MacOS
brew "mole" if OS.mac?

cask_args appdir: "~/Applications"

cask "font-jetbrains-mono-nerd-font"
cask "ghostty"
cask "krita"
cask "nikitabobko/tap/aerospace", trusted: true
cask "raspberry-pi-imager"
cask "the-unarchiver"
cask "ungoogled-chromium"
cask "wezterm"
