# Global
brew "akopdev/formulas/nbcat", trusted: true
brew "awscli"
brew "basedpyright"
brew "bash-language-server"
brew "bat"
brew "bc"
brew "bib-tool"
brew "cask"
brew "charmbracelet/tap/crush", trusted: true
brew "cookiecutter"
brew "ctop"
brew "dockerfile-language-server"
brew "dosfstools"
brew "ec"
brew "eslint"
brew "eza"
brew "fd"
brew "fx"
brew "fzf"
brew "gh"
brew "git"
brew "git-delta"
brew "glow"
brew "gnupg"
brew "go"
brew "gopls"
brew "hashicorp/tap/terraform", trusted: true
brew "helm"
brew "htop"
brew "hugo"
brew "imagemagick"
brew "irssi"
brew "jq"
brew "k9s"
brew "kubernetes-cli"
brew "lazysql"
brew "lua-language-server"
brew "mtools"
brew "ncdu"
brew "neovim"
brew "node"
brew "ollama"
brew "pass"
brew "pgcli"
brew "php"
brew "podman"
brew "podman-compose"
brew "profanity"
brew "python@3.13"
brew "qemu"
brew "ripgrep"
brew "sheets"
brew "stormy"
brew "syncthing"
brew "tea"
brew "terraform-ls"
brew "tmux"
brew "typescript"
brew "typescript-language-server"
brew "uv"
brew "vi-sql"
brew "wget"
brew "wifitui"
brew "xclip"
brew "yaml-language-server"
brew "yarn", link: false
brew "zinit"

cargo "ghgrab"

# Linux
if OS.linux?
  flatpak "org.wezfurlong.wezterm"
  flatpak "io.github.ungoogled_software.ungoogled_chromium"
end

# MacOS
if OS.mac?
  brew "mole"

  cask_args appdir: "~/Applications"

  cask "font-jetbrains-mono-nerd-font"
  cask "ghostty"
  cask "krita"
  cask "nikitabobko/tap/aerospace", trusted: true
  cask "raspberry-pi-imager"
  cask "syncthing-app"
  cask "the-unarchiver"
  cask "ungoogled-chromium"
  cask "wezterm"
end
