name: Publish release
on:
  release:
    types: [published]
jobs:
  build:
    name: Build and publish application
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get release version
        id: get_version
        run: echo ::set-output name=version::${GITHUB_REF#refs/tags/}

      - name: Build application container
        run: docker build . --tag ${{ github.repository }}:${{ steps.get_version.outputs.version }}

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            ${{ github.repository }}:stable
            ${{ github.repository }}:${{ steps.get_version.outputs.version }}
